spring:
  application:
    name: messaging-stomp-websocket-complete

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          naver:
            client-id: rGBK9I5882WT2X9ysfxh
            client-secret: WNMmTOrB2H
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
              - username
              - phone

          kakao:
            client-id: 75c8bfb6c3e2568c7828c7b198b1d264
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - phone_number
              - name
              - profile_nickname

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: classpath:/static,file:profile/, posting-media/

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size: 30
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret: v^K#V@igLXJrBvgY^%gKGy4-GsY51jrun:?C38FY?8h%]t_rd]E@nhL?de3tR>?

logging:
  level:
    org:
      springframework:
        web: INFO

server:
  address: 0.0.0.0
  port: 8080

naver:
  client-id: rGBK9I5882WT2X9ysfxh
  secret: WNMmTOrB2H

naver-cloud:
  client-id: eikw0ynuwx
  secret: F6gjeV4EAL9GvikpEs3Jey7CCJ1HO53b60Y0TTKc

tour-api:
  serviceKey: cxtbTLbpx9N%2FaG8%2BHZPEINXBbq6cMJ%2B4Xkhr4fVQIwzPX8YDEX%2F0O1oEfDecBvKbRRnUTcX9bvKf5uLbPj3m%2FA%3D%3D

odsay:
  apiKey: SVx00zK9WLRQiToxGqxTPiktotPUm/k+mg+jXt7oUAc