spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

        registration:
          naver:
            client-id: WL2LBTzd0v3Efgifo61I
            client-secret: cUkWA_5mWj
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
              - username
              - phone

          kakao:
            client-id: 9e20fc06a0e459584d32624d77feea95
            client-secret: xHzSepZoBtzjuzRHB1YyfXZOtWCSqTWG
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - phone_number
              - name
              - profile_nickname

          google:
            client-id: 720661749698-7icq3csknksk3u0cfum7999esncujjrr.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile
              - email
  #              - https://www.googleapis.com/auth/user.phonenumbers.read

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static,file:profile/,file:posting_media/

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret: v^K#V@igLXJrBvgY^%gKGy4-GsY51jrun:?C38FY?8h%]t_rd]E@nhL?de3tR>?
